// MARK: - TestCodeGenerator File Generation
// Test file generation from extracted types.

import Foundation

extension TestCodeGenerator {
  /// Generate a complete test file for multiple types.
  public func generateTestFile(
    types: [ExtractedTypeInfo],
    sourceFile: String
  ) -> String {
    var lines: [String] = []

    let fileName = URL(fileURLWithPath: sourceFile)
      .deletingPathExtension()
      .lastPathComponent

    appendHeader(sourceFile: sourceFile, to: &lines)
    appendArbitraryExtensions(types: types, to: &lines)
    appendTestMarker(fileName: fileName, to: &lines)
    appendTests(types: types, to: &lines)

    return lines.joined(separator: "\n")
  }

  private func appendHeader(sourceFile: String, to lines: inout [String]) {
    // Generated test files use linter disable comments
    let disableComment = "// swift" + "lint" + ":disable file_header identifier_name"
    lines.append(disableComment)
    lines.append("// swiftformat:disable all")
    lines.append("// swift-format-ignore-file")
    lines.append("// Generated by InvariantSwift Ghostwriter")
    lines.append("// Source: \(sourceFile)")
    lines.append("// Generated: \(ISO8601DateFormatter().string(from: Date()))")
    lines.append("//")
    lines.append("// DO NOT EDIT - Regenerate with: swift package ghostwrite")
    lines.append("")
    lines.append("import Testing")
    lines.append("import Foundation")
    lines.append("@testable import InvariantSwift")
    lines.append("")
  }

  private func appendArbitraryExtensions(
    types: [ExtractedTypeInfo],
    to lines: inout [String]
  ) {
    let typesNeedingArbitrary = types.filter {
      !$0.hasArbitraryAttribute && !$0.properties.isEmpty
        && !Self.knownGeneratableTypes.contains($0.name)
    }

    guard !typesNeedingArbitrary.isEmpty else { return }

    lines.append("// MARK: - Auto-Generated Arbitrary Conformances")
    lines.append("")
    for type in typesNeedingArbitrary {
      lines.append(generateArbitraryExtension(for: type))
      lines.append("")
    }
  }

  private func appendTestMarker(fileName: String, to lines: inout [String]) {
    lines.append("// MARK: - \(fileName) Property Tests")
    lines.append("")
  }

  private func appendTests(types: [ExtractedTypeInfo], to lines: inout [String]) {
    for type in types {
      let patterns = detectPatterns(for: type)
      guard !patterns.isEmpty else { continue }

      lines.append("// MARK: - \(type.name)")
      lines.append("")

      for pattern in patterns {
        let testCode = generateTest(for: type, pattern: pattern)
        lines.append(testCode)
        lines.append("")
      }
    }
  }
}
