// MARK: - Test Code Generator
// Generates property test code from extracted type information.

import Foundation

// MARK: - Test Pattern

/// Test patterns that can be generated.
public enum GhostwriterTestPattern: String, CaseIterable, Codable, Sendable {
  case codableRoundtrip
  case equatableReflexive
  case equatableSymmetric
  case equatableTransitive
  case hashableConsistency
  case comparableIrreflexive
  case comparableAsymmetric
  case comparableTransitive
  case comparableTrichotomy

  public static var equatableLaws: [GhostwriterTestPattern] {
    [.equatableReflexive, .equatableSymmetric, .equatableTransitive]
  }

  public static var comparableLaws: [GhostwriterTestPattern] {
    [.comparableIrreflexive, .comparableAsymmetric, .comparableTransitive, .comparableTrichotomy]
  }
}

// MARK: - Test Generator

/// Generates property test code from extracted types.
public struct TestCodeGenerator {

  public init() {}

  // MARK: - Pattern Detection

  /// Detect applicable test patterns for a type based on conformances.
  public func detectPatterns(for type: ExtractedTypeInfo) -> [GhostwriterTestPattern] {
    var patterns = Set<GhostwriterTestPattern>()

    for conformance in type.conformances {
      switch conformance {
      case "Codable":
        // Codable roundtrip needs Equatable to verify
        if type.conformances.contains("Equatable") || type.conformances.contains("Hashable") {
          patterns.insert(.codableRoundtrip)
        }
      case "Equatable":
        GhostwriterTestPattern.equatableLaws.forEach { patterns.insert($0) }
      case "Hashable":
        patterns.insert(.hashableConsistency)
        GhostwriterTestPattern.equatableLaws.forEach { patterns.insert($0) }
      case "Comparable":
        GhostwriterTestPattern.comparableLaws.forEach { patterns.insert($0) }
      default:
        break
      }
    }

    return Array(patterns).sorted { $0.rawValue < $1.rawValue }
  }

  // MARK: - Test File Generation

  /// Generate a complete test file for multiple types.
  public func generateTestFile(
    types: [ExtractedTypeInfo],
    sourceFile: String
  ) -> String {
    var lines: [String] = []

    let fileName = URL(fileURLWithPath: sourceFile)
      .deletingPathExtension()
      .lastPathComponent

    // Header
    lines.append("// swiftlint:disable file_header identifier_name")
    lines.append("// swiftformat:disable all")
    lines.append("// swift-format-ignore-file")
    lines.append("// Generated by InvariantSwift Ghostwriter")
    lines.append("// Source: \(sourceFile)")
    lines.append("// Generated: \(ISO8601DateFormatter().string(from: Date()))")
    lines.append("//")
    lines.append("// DO NOT EDIT - Regenerate with: swift package ghostwrite")
    lines.append("")
    lines.append("import Testing")
    lines.append("import Foundation")
    lines.append("@testable import InvariantSwift")
    lines.append("")

    // Generate Arbitrary extensions for types that need them
    // Skip types with @Arbitrary attribute and types that are known to have built-in generators
    let knownTypes: Set<String> = [
      "Int", "Int8", "Int16", "Int32", "Int64",
      "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
      "Double", "Float", "Bool", "String", "Character",
      "Date", "UUID", "URL", "Data", "Seed", "Size",
    ]
    let typesNeedingArbitrary = types.filter {
      !$0.hasArbitraryAttribute && !$0.properties.isEmpty && !knownTypes.contains($0.name)
    }
    if !typesNeedingArbitrary.isEmpty {
      lines.append("// MARK: - Auto-Generated Arbitrary Conformances")
      lines.append("")
      for type in typesNeedingArbitrary {
        lines.append(generateArbitraryExtension(for: type))
        lines.append("")
      }
    }

    lines.append("// MARK: - \(fileName) Property Tests")
    lines.append("")

    // Generate tests for each type
    for type in types {
      let patterns = detectPatterns(for: type)
      guard !patterns.isEmpty else { continue }

      lines.append("// MARK: - \(type.name)")
      lines.append("")

      for pattern in patterns {
        let testCode = generateTest(for: type, pattern: pattern)
        lines.append(testCode)
        lines.append("")
      }
    }

    return lines.joined(separator: "\n")
  }

  /// Generate Arbitrary extension for a type.
  public func generateArbitraryExtension(for type: ExtractedTypeInfo) -> String {
    let propGenerators = type.properties.map { prop in
      "\(prop.name): \(generatorExpression(for: prop.typeName))"
    }

    return """
      extension \(type.name): Arbitrary {
        public static var arbitrary: Gen<\(type.name)> {
          Gen.compose { composer in
            \(type.name)(
              \(propGenerators.joined(separator: ",\n        "))
            )
          }
        }
      }
      """
  }

  /// Generate the Gen expression for a type.
  private func generatorExpression(for typeName: String) -> String {
    var cleanedType =
      typeName
      .replacingOccurrences(of: "?", with: "")
      .replacingOccurrences(of: "!", with: "")
      .trimmingCharacters(in: .whitespaces)

    let isOptional = typeName.contains("?") || typeName.hasPrefix("Optional<")

    // Handle Optional<T>
    if cleanedType.hasPrefix("Optional<") && cleanedType.hasSuffix(">") {
      cleanedType = String(cleanedType.dropFirst(9).dropLast())
    }

    let baseExpr: String

    // Handle Array<T> or [T]
    if cleanedType.hasPrefix("Array<") && cleanedType.hasSuffix(">") {
      let inner = String(cleanedType.dropFirst(6).dropLast())
      baseExpr = "composer.generate(using: Gen.array(of: \(inner).arbitrary))"
    } else if cleanedType.hasPrefix("[") && cleanedType.hasSuffix("]") && !cleanedType.contains(":")
    {
      let inner = String(cleanedType.dropFirst().dropLast())
      baseExpr = "composer.generate(using: Gen.array(of: \(inner).arbitrary))"
    }
    // Handle Set<T>
    else if cleanedType.hasPrefix("Set<") && cleanedType.hasSuffix(">") {
      let inner = String(cleanedType.dropFirst(4).dropLast())
      baseExpr = "Set(composer.generate(using: Gen.array(of: \(inner).arbitrary)))"
    }
    // Handle Dictionary
    else if cleanedType.hasPrefix("Dictionary<")
      || (cleanedType.hasPrefix("[") && cleanedType.contains(":"))
    {
      baseExpr = "[:]"  // Empty dictionary as fallback
    }
    // Standard types
    else {
      baseExpr = "composer.generate(using: \(cleanedType).arbitrary)"
    }

    if isOptional {
      return "composer.generate(using: Gen.optional(\(cleanedType).arbitrary))"
    }

    return baseExpr
  }

  // MARK: - Individual Test Generation

  /// Generate a single test for a type and pattern.
  public func generateTest(
    for type: ExtractedTypeInfo,
    pattern: GhostwriterTestPattern
  ) -> String {
    let typeName = type.name

    switch pattern {
    case .codableRoundtrip:
      return """
        /// Codable roundtrip: encoding and decoding preserves value.
        @PropertyTest
        func test\(typeName)_codableRoundtrip(value: \(typeName)) throws {
          let encoded = try JSONEncoder().encode(value)
          let decoded = try JSONDecoder().decode(\(typeName).self, from: encoded)
          #expect(decoded == value, "Codable roundtrip should preserve value")
        }
        """

    case .equatableReflexive:
      return """
        /// Equatable reflexivity: x == x for all x.
        @PropertyTest
        func test\(typeName)_equatableReflexive(value: \(typeName)) {
          #expect(value == value, "Reflexivity: x == x")
        }
        """

    case .equatableSymmetric:
      return """
        /// Equatable symmetry: x == y implies y == x.
        @PropertyTest
        func test\(typeName)_equatableSymmetric(a: \(typeName), b: \(typeName)) {
          if a == b {
            #expect(b == a, "Symmetry: a == b implies b == a")
          }
        }
        """

    case .equatableTransitive:
      return """
        /// Equatable transitivity: x == y && y == z implies x == z.
        @PropertyTest
        func test\(typeName)_equatableTransitive(a: \(typeName), b: \(typeName), c: \(typeName)) {
          if a == b && b == c {
            #expect(a == c, "Transitivity: a == b && b == c implies a == c")
          }
        }
        """

    case .hashableConsistency:
      return """
        /// Hashable consistency: equal values must have equal hash values.
        @PropertyTest
        func test\(typeName)_hashableConsistency(a: \(typeName), b: \(typeName)) {
          if a == b {
            #expect(a.hashValue == b.hashValue, "Equal values must have equal hash values")
          }
        }
        """

    case .comparableIrreflexive:
      return """
        /// Comparable irreflexivity: !(x < x) for all x.
        @PropertyTest
        func test\(typeName)_comparableIrreflexive(value: \(typeName)) {
          #expect(!(value < value), "Irreflexivity: !(x < x)")
        }
        """

    case .comparableAsymmetric:
      return """
        /// Comparable asymmetry: x < y implies !(y < x).
        @PropertyTest
        func test\(typeName)_comparableAsymmetric(a: \(typeName), b: \(typeName)) {
          if a < b {
            #expect(!(b < a), "Asymmetry: a < b implies !(b < a)")
          }
        }
        """

    case .comparableTransitive:
      return """
        /// Comparable transitivity: x < y && y < z implies x < z.
        @PropertyTest
        func test\(typeName)_comparableTransitive(a: \(typeName), b: \(typeName), c: \(typeName)) {
          if a < b && b < c {
            #expect(a < c, "Transitivity: a < b && b < c implies a < c")
          }
        }
        """

    case .comparableTrichotomy:
      return """
        /// Comparable trichotomy: exactly one of <, ==, > holds.
        @PropertyTest
        func test\(typeName)_comparableTrichotomy(a: \(typeName), b: \(typeName)) {
          let isLess = a < b
          let isEqual = a == b
          let isGreater = b < a
          let exactlyOne = [isLess, isEqual, isGreater].filter { $0 }.count == 1
          #expect(exactlyOne, "Trichotomy: exactly one of <, ==, > holds")
        }
        """
    }
  }
}
