// MARK: - Test Code Generator
// Generates property test code from extracted type information.

import Foundation

// MARK: - Test Pattern

/// Test patterns that can be generated.
public enum GhostwriterTestPattern: String, CaseIterable, Codable, Sendable {
  case codableRoundtrip
  case equatableReflexive
  case equatableSymmetric
  case equatableTransitive
  case hashableConsistency
  case comparableIrreflexive
  case comparableAsymmetric
  case comparableTransitive
  case comparableTrichotomy

  public static var equatableLaws: [Self] {
    [.equatableReflexive, .equatableSymmetric, .equatableTransitive]
  }

  public static var comparableLaws: [Self] {
    [.comparableIrreflexive, .comparableAsymmetric, .comparableTransitive, .comparableTrichotomy]
  }
}

// MARK: - Generator Result

/// Result of attempting to generate an Arbitrary conformance for a property.
public enum GeneratorResult: Sendable {
  /// Generator can be automatically created.
  case success(String)
  /// Generator cannot be automatically created; requires user input.
  case todoRequired(typeName: String, reason: String)
}

/// Result of generating an Arbitrary extension with TODO tracking.
public struct ArbitraryGenerationResult: Sendable {
  /// The generated extension code.
  public let code: String
  /// Property names that require TODO comments.
  public let todoProperties: [String]
  /// Whether the extension was fully auto-generated.
  public var isFullyGenerated: Bool { todoProperties.isEmpty }

  public init(code: String, todoProperties: [String]) {
    self.code = code
    self.todoProperties = todoProperties
  }
}

// MARK: - Test Generator

/// Generates property test code from extracted types.
public struct TestCodeGenerator {

  public init() {}

  // MARK: - Pattern Detection

  /// Detect applicable test patterns for a type based on conformances.
  public func detectPatterns(for type: ExtractedTypeInfo) -> [GhostwriterTestPattern] {
    var patterns = Set<GhostwriterTestPattern>()

    for conformance in type.conformances {
      switch conformance {
      case "Codable":
        // Codable roundtrip needs Equatable to verify
        if type.conformances.contains("Equatable") || type.conformances.contains("Hashable") {
          patterns.insert(.codableRoundtrip)
        }

      case "Equatable":
        GhostwriterTestPattern.equatableLaws.forEach { patterns.insert($0) }

      case "Hashable":
        patterns.insert(.hashableConsistency)
        GhostwriterTestPattern.equatableLaws.forEach { patterns.insert($0) }

      case "Comparable":
        GhostwriterTestPattern.comparableLaws.forEach { patterns.insert($0) }

      default:
        break
      }
    }

    return Array(patterns).sorted { $0.rawValue < $1.rawValue }
  }

  // MARK: - Test File Generation

  /// Generate a complete test file for multiple types.
  public func generateTestFile(
    types: [ExtractedTypeInfo],
    sourceFile: String
  ) -> String {
    var lines: [String] = []

    let fileName = URL(fileURLWithPath: sourceFile)
      .deletingPathExtension()
      .lastPathComponent

    // Header
    lines.append("// swiftlint:disable file_header identifier_name")
    lines.append("// swiftformat:disable all")
    lines.append("// swift-format-ignore-file")
    lines.append("// Generated by InvariantSwift Ghostwriter")
    lines.append("// Source: \(sourceFile)")
    lines.append("// Generated: \(ISO8601DateFormatter().string(from: Date()))")
    lines.append("//")
    lines.append("// DO NOT EDIT - Regenerate with: swift package ghostwrite")
    lines.append("")
    lines.append("import Testing")
    lines.append("import Foundation")
    lines.append("@testable import InvariantSwift")
    lines.append("")

    // Generate Arbitrary extensions for types that need them
    // Skip types with @Arbitrary attribute and types that are known to have built-in generators
    let knownTypes: Set<String> = [
      "Int", "Int8", "Int16", "Int32", "Int64",
      "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
      "Double", "Float", "Bool", "String", "Character",
      "Date", "UUID", "URL", "Data", "Seed", "Size",
    ]
    let typesNeedingArbitrary = types.filter {
      !$0.hasArbitraryAttribute && !$0.properties.isEmpty && !knownTypes.contains($0.name)
    }
    if !typesNeedingArbitrary.isEmpty {
      lines.append("// MARK: - Auto-Generated Arbitrary Conformances")
      lines.append("")
      for type in typesNeedingArbitrary {
        lines.append(generateArbitraryExtension(for: type))
        lines.append("")
      }
    }

    lines.append("// MARK: - \(fileName) Property Tests")
    lines.append("")

    // Generate tests for each type
    for type in types {
      let patterns = detectPatterns(for: type)
      guard !patterns.isEmpty else { continue }

      lines.append("// MARK: - \(type.name)")
      lines.append("")

      for pattern in patterns {
        let testCode = generateTest(for: type, pattern: pattern)
        lines.append(testCode)
        lines.append("")
      }
    }

    return lines.joined(separator: "\n")
  }

  /// Generate Arbitrary extension for a type with TODO tracking.
  public func generateArbitraryExtensionResult(
    for type: ExtractedTypeInfo
  ) -> ArbitraryGenerationResult {
    var todoProperties: [String] = []
    let propGenerators = type.properties.map { prop in
      let result = generatorResult(for: prop.typeName)
      switch result {
      case .success(let expr):
        return "\(prop.name): \(expr)"

      case .todoRequired(let typeName, _):
        todoProperties.append(prop.name)
        return
          "\(prop.name): /* TODO: supply generator for \(typeName) */ composer.generate(using: \(typeName).arbitrary)"
      }
    }

    let code = """
      extension \(type.name): Arbitrary {
        public static var arbitrary: Gen<\(type.name)> {
          Gen.compose { composer in
            \(type.name)(
              \(propGenerators.joined(separator: ",\n        "))
            )
          }
        }
      }
      """

    return ArbitraryGenerationResult(code: code, todoProperties: todoProperties)
  }

  /// Generate Arbitrary extension for a type.
  /// Backward compatible method that uses generateArbitraryExtensionResult internally.
  public func generateArbitraryExtension(for type: ExtractedTypeInfo) -> String {
    generateArbitraryExtensionResult(for: type).code
  }

  // MARK: - Generator Result Analysis

  /// Known types that have built-in generators.
  private static let knownGeneratableTypes: Set<String> = [
    // Primitives
    "Int", "Int8", "Int16", "Int32", "Int64",
    "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
    "Double", "Float", "Bool", "String", "Character",
    // Foundation types
    "Date", "UUID", "URL", "Data",
    // Core types
    "Seed", "Size",
  ]

  /// Check if a type can have Arbitrary auto-generated (at least one property generatable).
  public func canAutoGenerateArbitrary(for type: ExtractedTypeInfo) -> Bool {
    // Must have at least one property
    guard !type.properties.isEmpty else { return false }

    // At least one property must be generatable
    return type.properties.contains { prop in
      let result = generatorResult(for: prop.typeName)
      if case .success = result {
        return true
      }
      return false
    }
  }

  /// Check if a type can be fully auto-generated (all properties generatable).
  public func canFullyGenerateArbitrary(for type: ExtractedTypeInfo) -> Bool {
    // Must have at least one property
    guard !type.properties.isEmpty else { return false }

    // All properties must be generatable
    return type.properties.allSatisfy { prop in
      let result = generatorResult(for: prop.typeName)
      if case .success = result {
        return true
      }
      return false
    }
  }

  /// Determine generator result for a property type.
  /// Returns `.success(expr)` with generator expression if generatable,
  /// or `.todoRequired` with reason if not.
  public func generatorResult(for typeName: String) -> GeneratorResult {
    var cleanedType =
      typeName
      .replacingOccurrences(of: "?", with: "")
      .replacingOccurrences(of: "!", with: "")
      .trimmingCharacters(in: .whitespaces)

    let isOptional = typeName.contains("?") || typeName.hasPrefix("Optional<")

    // Handle Optional<T>
    if cleanedType.hasPrefix("Optional<") && cleanedType.hasSuffix(">") {
      cleanedType = String(cleanedType.dropFirst(9).dropLast())
    }

    // Recursively check inner type
    let innerResult = checkInnerTypeResult(for: cleanedType)

    // Wrap in optional if needed
    switch innerResult {
    case .success(let expr):
      return .success(isOptional ? "composer.generate(using: Gen.optional(\(expr)))" : expr)

    case .todoRequired:
      return innerResult
    }
  }

  /// Check generator result for inner (non-optional) type
  private func checkInnerTypeResult(for cleanedType: String) -> GeneratorResult {
    // Handle Array<T> or [T]
    if cleanedType.hasPrefix("Array<") && cleanedType.hasSuffix(">") {
      let inner = String(cleanedType.dropFirst(6).dropLast())
      return checkArrayResult(inner: inner, wrapper: "[\(inner)]")
    }
    if cleanedType.hasPrefix("[") && cleanedType.hasSuffix("]") && !cleanedType.contains(":") {
      let inner = String(cleanedType.dropFirst().dropLast())
      return checkArrayResult(inner: inner, wrapper: "[\(inner)]")
    }
    // Handle Set<T>
    if cleanedType.hasPrefix("Set<") && cleanedType.hasSuffix(">") {
      let inner = String(cleanedType.dropFirst(4).dropLast())
      return checkSetResult(inner: inner)
    }
    // Handle Dictionary<K, V> or [K: V]
    if cleanedType.hasPrefix("Dictionary<") && cleanedType.hasSuffix(">") {
      let inner = String(cleanedType.dropFirst(11).dropLast())
      return checkDictionaryResult(inner: inner, wrapper: "Dictionary<\(inner)>")
    }
    if cleanedType.hasPrefix("[") && cleanedType.contains(":") && cleanedType.hasSuffix("]") {
      let inner = String(cleanedType.dropFirst().dropLast())
      return checkDictionaryResult(inner: inner, wrapper: cleanedType)
    }
    // Standard types
    if Self.knownGeneratableTypes.contains(cleanedType) {
      return .success("composer.generate(using: \(cleanedType).arbitrary)")
    }
    return .todoRequired(
      typeName: cleanedType,
      reason: "Type does not have a known generator"
    )
  }

  /// Check array type generation
  private func checkArrayResult(inner: String, wrapper: String) -> GeneratorResult {
    let innerCheck = generatorResult(for: inner)
    switch innerCheck {
    case .success:
      return .success("composer.generate(using: Gen.array(of: \(inner).arbitrary))")

    case .todoRequired(_, let reason):
      return .todoRequired(
        typeName: wrapper,
        reason: "Array element type cannot be generated: \(reason)"
      )
    }
  }

  /// Check set type generation
  private func checkSetResult(inner: String) -> GeneratorResult {
    let innerCheck = generatorResult(for: inner)
    switch innerCheck {
    case .success:
      return .success("Set(composer.generate(using: Gen.array(of: \(inner).arbitrary)))")

    case .todoRequired(let innerTypeName, let reason):
      return .todoRequired(
        typeName: "Set<\(innerTypeName)>",
        reason: "Set element type cannot be generated: \(reason)"
      )
    }
  }

  /// Check dictionary type generation
  /// Handles Dictionary<K, V> and [K: V] by splitting on comma and recursively checking key/value types
  private func checkDictionaryResult(inner: String, wrapper: String) -> GeneratorResult {
    // Split "K, V" into key and value types
    // Simple comma split works for most cases (Int, String), but not for nested generics
    // For now, handle simple cases; complex nested dictionaries will still return todoRequired
    let components = inner.split(separator: ",", maxSplits: 1).map {
      $0.trimmingCharacters(in: .whitespaces)
    }

    guard components.count == 2 else {
      return .todoRequired(
        typeName: wrapper,
        reason: "Cannot parse dictionary key/value types from '\(inner)'"
      )
    }

    let keyType = components[0]
    let valueType = components[1]

    // Check if key type is generatable
    let keyCheck = generatorResult(for: keyType)
    guard case .success = keyCheck else {
      if case .todoRequired(_, let reason) = keyCheck {
        return .todoRequired(
          typeName: wrapper,
          reason: "Dictionary key type cannot be generated: \(reason)"
        )
      }
      return keyCheck
    }

    // Check if value type is generatable
    let valueCheck = generatorResult(for: valueType)
    guard case .success = valueCheck else {
      if case .todoRequired(_, let reason) = valueCheck {
        return .todoRequired(
          typeName: wrapper,
          reason: "Dictionary value type cannot be generated: \(reason)"
        )
      }
      return valueCheck
    }

    // Both key and value are generatable - construct dictionary generator
    return .success(
      "Dictionary(uniqueKeysWithValues: composer.generate(using: Gen.array(of: Gen.zip(\(keyType).arbitrary, \(valueType).arbitrary))))"
    )
  }

  /// Generate the Gen expression for a type.
  /// Backward compatible method that uses generatorResult internally.
  private func generatorExpression(for typeName: String) -> String {
    let result = generatorResult(for: typeName)
    switch result {
    case .success(let expr):
      return expr

    case .todoRequired(let type, _):
      // Emit TODO comment for ungeneratable types (Hypothesis pattern)
      return "/* TODO: supply generator for \(type) */ composer.generate(using: \(type).arbitrary)"
    }
  }

  // MARK: - Individual Test Generation
  // Implementation moved to TestCodeGenerator+Patterns.swift extension
}
