import InvariantSwiftCore
import InvariantSwift
import Testing

/// Integration tests that verify the actual execution of property tests
/// generated by the @PropertyTest macro expansion pattern.
///
/// These tests validate:
/// 1. Property creation and configuration works correctly
/// 2. Generator inference produces valid generators
/// 3. PropertyRunner executes and returns correct results
/// 4. Result handling (success, failure, gaveUp) works as expected
struct PropertyMacroIntegrationTests {

  // MARK: - Basic Property Execution Tests

  @Test("Property test with Int parameter succeeds for valid property")
  func propertyTestIntSucceeds() throws {
    // This simulates the expansion of:
    // @PropertyTest func testInt(x: Int) { #expect(x == x) }

    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      // swiftlint:disable:next identical_operands
      x == x  // Always true - identity property (testing reflexivity)
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 100)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break  // Expected
    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test with String parameter succeeds for valid property")
  func propertyTestStringSucceeds() throws {
    let generator = Gen<String>.string
    let property = Property(generator: generator) { (_: String) in
      true  // String identity: always passes
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 100)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break  // Expected
    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test with Bool parameter succeeds for valid property")
  func propertyTestBoolSucceeds() throws {
    let generator = Gen<Bool>.bool
    let property = Property(generator: generator) { (value: Bool) in
      // swiftlint:disable:next identical_operands
      value == value  // Identity (testing reflexivity)
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 100)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  // MARK: - Multiple Parameter Tests (Gen.zip pattern)

  @Test("Property test with two Int parameters using Gen.zip")
  func propertyTestTwoIntsWithZip() throws {
    // Simulates expansion with multiple parameters:
    // @PropertyTest func test(a: Int, b: Int) { #expect((a + b) - a == b) }

    let generator = Gen<Int>.int.zip(Gen<Int>.int)
    let property = Property(generator: generator) { (tuple: (Int, Int)) in
      let (lhs, rhs) = tuple
      // Addition commutativity (works for all Int, avoiding overflow)
      return lhs &+ rhs == rhs &+ lhs
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 100)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test with three parameters using Gen.zip3")
  func propertyTestThreeParamsWithZip() throws {
    // swiftlint:disable:next large_tuple
    let generator = Gen<(Int, String, Bool)>.zip3(
      Gen<Int>.int,
      Gen<String>.string,
      Gen<Bool>.bool
    )
    // swiftlint:disable:next large_tuple
    let property = Property(generator: generator) { (_: (Int, String, Bool)) in
      true  // Property always succeeds - testing Gen.zip3 integration
    }

    let config = PropertyConfig(iterations: 50, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  // MARK: - Collection Type Generator Tests

  @Test("Property test with Array<Int> parameter")
  func propertyTestArrayInt() throws {
    // Simulates: @PropertyTest func test(arr: [Int]) { ... }
    let generator = Gen<[Int]>.array(Gen<Int>.int)
    let property = Property<[Int]>(generator: generator) { arr in
      !arr.isEmpty || arr.isEmpty  // Array identity: always passes
    }

    let config = PropertyConfig(iterations: 50, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test with Set<Int> parameter")
  func propertyTestSetInt() throws {
    let generator = Gen<Set<Int>>.set(Gen<Int>.int)
    let property = Property<Set<Int>>(generator: generator) { set in
      !set.isEmpty || set.isEmpty  // Set identity: always passes
    }

    let config = PropertyConfig(iterations: 50, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test with Dictionary<String, Int> parameter")
  func propertyTestDictionary() throws {
    let generator = Gen<[String: Int]>.dictionary(Gen<String>.string, Gen<Int>.int)
    let property = Property<[String: Int]>(generator: generator) { dict in
      !dict.isEmpty || dict.isEmpty  // Dictionary identity: always passes
    }

    let config = PropertyConfig(iterations: 50, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  // MARK: - Optional Type Generator Tests

  @Test("Property test with Optional<Int> parameter")
  func propertyTestOptionalInt() throws {
    let generator = OptionalGen.optional(valueGen: Gen<Int>.int)
    let property = Property<Int?>(generator: generator) { opt in
      // Optional is either nil or has a value
      opt == nil || opt != nil
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  // MARK: - Failure Detection Tests

  @Test("Property test detects failure and provides counterexample")
  func propertyTestDetectsFailure() throws {
    // Property that will fail: not all Ints are positive
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      x > 0  // Fails for 0 and negative numbers
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 100)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      Issue.record("Property should have found a counterexample")

    case .failure(let counterexample, let iterations, let shrunk, _, _):
      #expect(iterations > 0, "Should have run at least one iteration")
      // The shrunk counterexample should be minimal (likely 0 or -1)
      #expect(shrunk <= 0, "Shrunk value should be non-positive: \(shrunk)")
      _ = counterexample  // Counterexample captured
    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  @Test("Property test shrinks to minimal counterexample")
  func propertyTestShrinksToMinimal() throws {
    // Property fails for values >= 100
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      x < 100
    }

    let config = PropertyConfig(iterations: 1000, maxShrinks: 1000)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      // May succeed if no value >= 100 was generated
      break

    case .failure(_, _, let shrunk, _, _):
      // If found, shrunk should be exactly 100 (minimal failing value)
      #expect(shrunk == 100, "Shrunk counterexample should be 100, got \(shrunk)")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }

  // MARK: - Seed Determinism Tests

  @Test("Property test with seed produces deterministic results")
  func propertyTestSeedDeterminism() throws {
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      // swiftlint:disable:next identical_operands
      x == x  // Testing reflexivity
    }

    let seed = Seed(value: 12345)
    let config1 = PropertyConfig(iterations: 50, maxShrinks: 50, seed: seed)
    let config2 = PropertyConfig(iterations: 50, maxShrinks: 50, seed: seed)

    let result1 = runPropertySynchronously(property, config: config1)
    let result2 = runPropertySynchronously(property, config: config2)

    // Both should succeed with same seed
    switch (result1, result2) {
    case (.success, .success):
      break  // Expected
    default:
      Issue.record("Both runs with same seed should produce same result")
    }
  }

  // MARK: - Configuration Tests

  @Test("Property test respects iteration count")
  func propertyTestRespectsIterationCount() throws {
    // Verify iteration count through result, not mutable counter
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (_: Int) in
      true
    }

    let config = PropertyConfig(iterations: 25, maxShrinks: 0)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success(let iterations):
      #expect(iterations == 25, "Should have run exactly 25 iterations, ran \(iterations)")

    case .failure, .gaveUp:
      Issue.record("Test should have succeeded")
    }
  }

  // MARK: - Edge Case Tests

  @Test("Property test handles empty string generation")
  func propertyTestHandlesEmptyString() throws {
    // Sample directly to verify empty strings can be generated
    let generator = Gen<String>.string
    var sawEmpty = false

    // Sample directly to avoid @Sendable closure capture issues
    for i in 0..<500 {
      let seed = Seed(value: UInt64(i))
      let size = Size(value: 5)  // Small size to increase chance of empty
      let s = generator.sample(size: size, seed: seed)
      if s.isEmpty {
        sawEmpty = true
        break
      }
    }

    // Empty string may or may not be generated depending on size parameter
    // Just verify we can sample without error
    _ = sawEmpty
  }

  @Test("Property test handles boundary Int values")
  func propertyTestHandlesBoundaryInts() throws {
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      // This property is true for all Ints including boundaries
      x >= Int.min && x <= Int.max
    }

    let config = PropertyConfig(iterations: 100, maxShrinks: 50)
    let result = runPropertySynchronously(property, config: config)

    switch result {
    case .success:
      break

    case .failure:
      Issue.record("Property should have succeeded for all Int values")

    case .gaveUp:
      Issue.record("Property should not have given up")
    }
  }
}

// MARK: - Generator Inference Integration Tests

/// Tests that verify the generators produced by GeneratorInference work correctly
/// when used in actual property tests.
struct GeneratorInferenceIntegrationTests {

  @Test("Inferred Int generator produces valid integers")
  func inferredIntGeneratorWorks() throws {
    // Gen<Int>.int is what GeneratorInference produces for Int
    let generator = Gen<Int>.int
    let property = Property(generator: generator) { (x: Int) in
      // Verify it's a valid Int (always true by type system)
      // swiftlint:disable:next identical_operands
      x == x  // Testing reflexivity
    }

    let result = runPropertySynchronously(
      property,
      config: PropertyConfig(iterations: 100, maxShrinks: 0)
    )
    #expect(result.isSuccess, "Inferred Int generator should work")
  }

  @Test("Inferred Double generator produces valid doubles")
  func inferredDoubleGeneratorWorks() throws {
    let generator = Gen<Double>.double
    let property = Property(generator: generator) { (x: Double) in
      // NaN is the only Double not equal to itself
      // swiftlint:disable:next identical_operands
      x.isNaN || x == x  // Testing NaN behavior
    }

    let result = runPropertySynchronously(
      property,
      config: PropertyConfig(iterations: 100, maxShrinks: 0)
    )
    #expect(result.isSuccess, "Inferred Double generator should work")
  }

  @Test("Inferred nested Array of Optional Int generator works")
  func inferredNestedGeneratorWorks() throws {
    // Gen.array(OptionalGen.optional(valueGen: Gen<Int>.int))
    let generator = Gen<[Int?]>.array(OptionalGen.optional(valueGen: Gen<Int>.int))
    let property = Property<[Int?]>(generator: generator) { arr in
      !arr.isEmpty || arr.isEmpty  // Array identity: always passes
    }

    let result = runPropertySynchronously(
      property,
      config: PropertyConfig(iterations: 50, maxShrinks: 0)
    )
    #expect(result.isSuccess, "Nested generator should work")
  }
}

// MARK: - Helper Extensions

extension PropertyResult {
  var isSuccess: Bool {
    if case .success = self { return true }
    return false
  }
}
