import Foundation
import MacroTemplateKit
import SwiftSyntax
import SwiftSyntaxBuilder

public enum GhostwriterExpansionRenderer {
  public static func render(file: GhostwriterGeneratedFile) -> String {
    var parts = renderHeader(for: file)

    if !file.arbitraryExtensions.isEmpty {
      parts.append("// MARK: - Auto-Generated Arbitrary Conformances")
      parts.append("")
      parts.append(
        file.arbitraryExtensions
          .map(render(arbitraryExtension:))
          .joined(separator: "\n\n")
      )
      parts.append("")
    }

    parts.append("// MARK: - \(file.suiteTitle)")
    parts.append("")

    for section in file.sections {
      guard !section.tests.isEmpty else { continue }
      parts.append("// MARK: - \(section.title)")
      parts.append("")
      parts.append(section.tests.map(render(test:)).joined(separator: "\n\n"))
      parts.append("")
    }

    return parts.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
  }

  public static func render(arbitraryExtension: GhostwriterGeneratedArbitraryExtension) -> String {
    let property = MacroTemplateAdapter.makeComputedProperty(
      accessLevel: .public,
      name: "arbitrary",
      type: "Gen<\(arbitraryExtension.typeName)>",
      isStatic: true,
      getterBody: CodeBlockSyntax {
        CodeBlockItemSyntax(
          item: .expr(
            composeCall(
              typeName: arbitraryExtension.typeName,
              propertyGenerators: arbitraryExtension.propertyGenerators
            )
          )
        )
      }
    )

    let extensionDecl = MacroTemplateAdapter.makeExtension(
      typeName: arbitraryExtension.typeName,
      conformances: ["Arbitrary"]
    )

    let memberBlock = MemberBlockSyntax(
      members: MemberBlockItemListSyntax([
        MemberBlockItemSyntax(decl: DeclSyntax(property))
      ])
    )

    return extensionDecl.with(\.memberBlock, memberBlock).description
  }

  public static func render(test: GhostwriterGeneratedTest) -> String {
    let function = MacroTemplateAdapter.makeFunction(
      attributes: [.init("PropertyTest")],
      name: test.functionName,
      canThrow: test.isThrowing,
      body: CodeBlockSyntax(
        statements: CodeBlockItemListSyntax(test.bodyStatements.map(render(statement:)))
      )
    )
    .with(\.leadingTrivia, [.docLineComment("/// \(test.docComment)"), .newlines(1)])

    return function.description
  }

  public static func renderExpression(_ expression: ExpansionExpr) -> String {
    render(expr: expression).description
  }

  private static func renderHeader(for file: GhostwriterGeneratedFile) -> [String] {
    [
      "// swiftlint:disable file_header identifier_name",
      "// swiftformat:disable all",
      "// swift-format-ignore-file",
      "// Generated by InvariantSwift Ghostwriter",
      "// Source: \(file.sourceFile)",
      "// Generated: \(file.generatedAt)",
      "//",
      "// DO NOT EDIT - Regenerate with: swift package ghostwrite",
      "",
    ] + file.imports.map(render(importDecl:)) + [""]
  }

  private static func render(importDecl: GhostwriterImport) -> String {
    importDecl.isTestable
      ? "@testable import \(importDecl.moduleName)"
      : "import \(importDecl.moduleName)"
  }

  private static func render(statement: ExpansionStatement) -> CodeBlockItemSyntax {
    switch statement {
    case .letBinding(let name, let initializer):
      return CodeBlockItemSyntax(
        item: .decl(
          DeclSyntax(
            VariableDeclSyntax(
              bindingSpecifier: .keyword(.let),
              bindings: PatternBindingListSyntax([
                PatternBindingSyntax(
                  pattern: IdentifierPatternSyntax(identifier: .identifier(name)),
                  initializer: InitializerClauseSyntax(value: render(expr: initializer))
                )
              ])
            )
          )
        )
      )

    case .ifStatement(let condition, let body):
      return CodeBlockItemSyntax(
        item: .expr(
          ExprSyntax(
            IfExprSyntax(
              conditions: ConditionElementListSyntax([
                ConditionElementSyntax(condition: .expression(render(expr: condition)))
              ]),
              body: CodeBlockSyntax(
                statements: CodeBlockItemListSyntax(body.map(render(statement:)))
              )
            )
          )
        )
      )

    case .expression(let expression):
      return CodeBlockItemSyntax(item: .expr(render(expr: expression)))

    case .expect(let condition, let message):
      return GhostwriterExpansionEscapeHatches.renderExpectation(
        condition: render(expr: condition),
        message: message
      )
    }
  }

  private static func render(expr: ExpansionExpr) -> ExprSyntax {
    switch expr {
    case .identifier(let name):
      return ExprSyntax(DeclReferenceExprSyntax(baseName: .identifier(name)))

    case .member(let base, let name):
      return ExprSyntax(
        MemberAccessExprSyntax(
          base: render(expr: base),
          declName: DeclReferenceExprSyntax(baseName: .identifier(name))
        )
      )

    case .call(let callee, let arguments, let trailingClosure):
      return renderCall(callee: callee, arguments: arguments, trailingClosure: trailingClosure)

    case .tryExpr(let expression):
      return ExprSyntax(TryExprSyntax(expression: render(expr: expression)))

    case .binary(let lhs, let op, let rhs):
      return ExprSyntax(
        SequenceExprSyntax {
          render(expr: lhs)
          BinaryOperatorExprSyntax(operator: .binaryOperator(op))
          render(expr: rhs)
        }
      )

    case .prefix(let op, let expression):
      return ExprSyntax(
        PrefixOperatorExprSyntax(
          operator: .prefixOperator(op),
          expression: render(expr: expression)
        )
      )

    case .array(let expressions):
      return ExprSyntax(
        ArrayExprSyntax(
          elements: ArrayElementListSyntax(
            expressions.map { expression in
              ArrayElementSyntax(expression: render(expr: expression))
            }
          )
        )
      )

    case .tuple(let expressions):
      return ExprSyntax(
        TupleExprSyntax(
          elements: LabeledExprListSyntax(
            expressions.map { expression in
              LabeledExprSyntax(expression: render(expr: expression))
            }
          )
        )
      )

    case .exactlyOneTrue(let expressions):
      return GhostwriterExpansionEscapeHatches.renderExactlyOneTrue(
        expressions.map(render(expr:))
      )
    }
  }

  private static func renderCall(
    callee: ExpansionExpr,
    arguments: [ExpansionArgument],
    trailingClosure: ExpansionClosure?
  ) -> ExprSyntax {
    ExprSyntax(
      FunctionCallExprSyntax(
        calledExpression: render(expr: callee),
        leftParen: trailingClosure == nil ? .leftParenToken() : nil,
        arguments: LabeledExprListSyntax(arguments.map(render(argument:))),
        rightParen: trailingClosure == nil ? .rightParenToken() : nil,
        trailingClosure: trailingClosure.map(render(closure:))
      )
    )
  }

  private static func render(argument: ExpansionArgument) -> LabeledExprSyntax {
    LabeledExprSyntax(
      label: argument.label.map { .identifier($0) },
      colon: argument.label == nil ? nil : .colonToken(trailingTrivia: .space),
      expression: render(expr: argument.expression)
    )
  }

  private static func render(closure: ExpansionClosure) -> ClosureExprSyntax {
    ClosureExprSyntax(
      signature: closure.parameters.isEmpty
        ? nil
        : ClosureSignatureSyntax(
          parameterClause: .simpleInput(
            ClosureShorthandParameterListSyntax(
              closure.parameters.map { name in
                ClosureShorthandParameterSyntax(name: .identifier(name))
              }
            )
          ),
          inKeyword: .keyword(.in, trailingTrivia: .space)
        ),
      statements: CodeBlockItemListSyntax(closure.bodyStatements.map(render(statement:)))
    )
  }

  private static func composeCall(
    typeName: String,
    propertyGenerators: [GhostwriterPropertyGenerator]
  ) -> ExprSyntax {
    render(
      expr: .variable("Gen").method(
        "compose",
        trailingClosure: ExpansionClosure(
          parameters: ["composer"],
          bodyStatements: [
            .expression(
              .call(
                callee: .identifier(typeName),
                arguments: propertyGenerators.map {
                  ExpansionArgument.labeled(
                    $0.name,
                    .variable("composer").method(
                      "generate",
                      arguments: [.labeled("using", $0.expression)]
                    )
                  )
                },
                trailingClosure: nil
              )
            )
          ]
        )
      )
    )
  }

  private static func propertyExpression(for property: GhostwriterPropertyGenerator) -> ExprSyntax {
    let expression = render(expr: property.expression)
    guard let todoComment = property.todoComment else {
      return expression
    }
    return expression.with(\.leadingTrivia, [.blockComment(todoComment), .spaces(1)])
  }
}
