import Foundation
import MacroTemplateKit
import SwiftBasicFormat
import SwiftSyntax
import SwiftSyntaxBuilder

// MARK: - Public Interface

public enum GhostwriterExpansionRenderer {
  public static func render(file: GhostwriterGeneratedFile) -> String {
    var parts = renderHeader(for: file)

    if !file.arbitraryExtensions.isEmpty {
      parts.append("// MARK: - Auto-Generated Arbitrary Conformances")
      parts.append("")
      parts.append(
        file.arbitraryExtensions
          .map(render(arbitraryExtension:))
          .joined(separator: "\n\n")
      )
      parts.append("")
    }

    parts.append("// MARK: - \(file.suiteTitle)")
    parts.append("")

    for section in file.sections {
      guard !section.tests.isEmpty else { continue }
      parts.append("// MARK: - \(section.title)")
      parts.append("")
      parts.append(section.tests.map(render(test:)).joined(separator: "\n\n"))
      parts.append("")
    }

    return parts.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
  }

  public static func render(
    arbitraryExtension ext: GhostwriterGeneratedArbitraryExtension
  ) -> String {
    let property = MacroTemplateAdapter.makeComputedProperty(
      accessLevel: .public,
      name: "arbitrary",
      type: "Gen<\(ext.typeName)>",
      isStatic: true,
      getterBody: CodeBlockSyntax {
        CodeBlockItemSyntax(
          item: .expr(
            composeCall(
              typeName: ext.typeName,
              propertyGenerators: ext.propertyGenerators
            )
          )
        )
      }
    )

    let extensionDecl = MacroTemplateAdapter.makeExtension(
      typeName: ext.typeName,
      conformances: ["Arbitrary"]
    )

    let memberBlock = MemberBlockSyntax(
      members: MemberBlockItemListSyntax([
        MemberBlockItemSyntax(decl: DeclSyntax(property))
      ])
    )

    return extensionDecl.with(\.memberBlock, memberBlock).description
  }

  public static func render(test: GhostwriterGeneratedTest) -> String {
    let params = FunctionParameterListSyntax(
      test.parameters.enumerated().map { index, param in
        var p = FunctionParameterSyntax(
          firstName: .identifier(param.name),
          colon: .colonToken(trailingTrivia: .space),
          type: TypeSyntax(stringLiteral: param.type)
        )
        if index < test.parameters.count - 1 {
          p = p.with(\.trailingComma, .commaToken(trailingTrivia: .space))
        }
        return p
      }
    )

    let function = MacroTemplateAdapter.makeFunction(
      attributes: [.init("PropertyTest")],
      name: test.functionName,
      canThrow: test.isThrowing,
      body: CodeBlockSyntax(
        statements: CodeBlockItemListSyntax(test.bodyStatements.map(render(statement:)))
      )
    )
    .with(
      \.signature.parameterClause,
      FunctionParameterClauseSyntax(parameters: params)
    )
    .with(\.leadingTrivia, [.docLineComment("/// \(test.docComment)"), .newlines(1)])

    return function.formatted().description
  }

  public static func renderExpression(_ expression: ExpansionExpr) -> String {
    render(expr: expression).description
  }
}

// MARK: - Private Rendering Helpers

private extension GhostwriterExpansionRenderer {
  static func renderHeader(for file: GhostwriterGeneratedFile) -> [String] {
    [
      "// swiftlint:disable file_header identifier_name",
      "// swiftformat:disable all",
      "// swift-format-ignore-file",
      "// Generated by InvariantSwift Ghostwriter",
      "// Source: \(file.sourceFile)",
      "// Generated: \(file.generatedAt)",
      "//",
      "// DO NOT EDIT - Regenerate with: swift package ghostwrite",
      "",
    ] + file.imports.map(render(importDecl:)) + [""]
  }

  static func render(importDecl: GhostwriterImport) -> String {
    importDecl.isTestable
      ? "@testable import \(importDecl.moduleName)"
      : "import \(importDecl.moduleName)"
  }

  static func render(statement: ExpansionStatement) -> CodeBlockItemSyntax {
    switch statement {
    case .letBinding(let name, let initializer):
      return CodeBlockItemSyntax(
        item: .decl(
          DeclSyntax(
            VariableDeclSyntax(
              bindingSpecifier: .keyword(.let),
              bindings: PatternBindingListSyntax([
                PatternBindingSyntax(
                  pattern: IdentifierPatternSyntax(identifier: .identifier(name)),
                  initializer: InitializerClauseSyntax(
                    value: render(expr: initializer)
                  )
                )
              ])
            )
          )
        )
      )

    case .ifStatement(let condition, let body):
      return CodeBlockItemSyntax(
        item: .expr(
          ExprSyntax(
            IfExprSyntax(
              conditions: ConditionElementListSyntax([
                ConditionElementSyntax(
                  condition: .expression(render(expr: condition))
                )
              ]),
              body: CodeBlockSyntax(
                statements: CodeBlockItemListSyntax(body.map(render(statement:)))
              )
            )
          )
        )
      )

    case .expression(let expression):
      return CodeBlockItemSyntax(item: .expr(render(expr: expression)))

    case .expect(let condition, let message):
      return GhostwriterExpansionEscapeHatches.renderExpectation(
        condition: render(expr: condition),
        message: message
      )
    }
  }

  static func render(expr: ExpansionExpr) -> ExprSyntax {
    switch expr {
    case .identifier(let name):
      return ExprSyntax(DeclReferenceExprSyntax(baseName: .identifier(name)))

    case .member(let base, let name):
      return ExprSyntax(
        MemberAccessExprSyntax(
          base: render(expr: base),
          declName: DeclReferenceExprSyntax(baseName: .identifier(name))
        )
      )

    case .call(let callee, let arguments, let trailingClosure):
      return renderCall(
        callee: callee,
        arguments: arguments,
        trailingClosure: trailingClosure
      )

    case .tryExpr(let expression):
      return ExprSyntax(TryExprSyntax(expression: render(expr: expression)))

    case .binary(let lhs, let op, let rhs):
      return ExprSyntax(
        SequenceExprSyntax {
          render(expr: lhs)
          BinaryOperatorExprSyntax(operator: .binaryOperator(op))
          render(expr: rhs)
        }
      )

    case .prefix(let op, let expression):
      return ExprSyntax(
        PrefixOperatorExprSyntax(
          operator: .prefixOperator(op),
          expression: render(expr: expression)
        )
      )

    case .array(let expressions):
      return ExprSyntax(
        ArrayExprSyntax(
          elements: ArrayElementListSyntax(
            expressions.map { expression in
              ArrayElementSyntax(expression: render(expr: expression))
            }
          )
        )
      )

    case .tuple(let expressions):
      return ExprSyntax(
        TupleExprSyntax(
          elements: LabeledExprListSyntax(
            expressions.map { expression in
              LabeledExprSyntax(expression: render(expr: expression))
            }
          )
        )
      )

    case .exactlyOneTrue(let expressions):
      return GhostwriterExpansionEscapeHatches.renderExactlyOneTrue(
        expressions.map(render(expr:))
      )
    }
  }

  static func renderCall(
    callee: ExpansionExpr,
    arguments: [ExpansionArgument],
    trailingClosure: ExpansionClosure?
  ) -> ExprSyntax {
    ExprSyntax(
      FunctionCallExprSyntax(
        calledExpression: render(expr: callee),
        leftParen: trailingClosure == nil ? .leftParenToken() : nil,
        arguments: LabeledExprListSyntax(arguments.map(render(argument:))),
        rightParen: trailingClosure == nil ? .rightParenToken() : nil,
        trailingClosure: trailingClosure.map(render(closure:))
      )
    )
  }

  static func render(argument: ExpansionArgument) -> LabeledExprSyntax {
    LabeledExprSyntax(
      label: argument.label.map { .identifier($0) },
      colon: argument.label == nil ? nil : .colonToken(trailingTrivia: .space),
      expression: render(expr: argument.expression)
    )
  }

  static func render(closure: ExpansionClosure) -> ClosureExprSyntax {
    ClosureExprSyntax(
      signature: closure.parameters.isEmpty
        ? nil
        : ClosureSignatureSyntax(
          parameterClause: .simpleInput(
            ClosureShorthandParameterListSyntax(
              closure.parameters.map { name in
                ClosureShorthandParameterSyntax(name: .identifier(name))
              }
            )
          ),
          inKeyword: .keyword(.in, trailingTrivia: .space)
        ),
      statements: CodeBlockItemListSyntax(closure.bodyStatements.map(render(statement:)))
    )
  }

  static func composeCall(
    typeName: String,
    propertyGenerators: [GhostwriterPropertyGenerator]
  ) -> ExprSyntax {
    // propertyGenerators[i].expression is already composer.generate(using: ...).
    // Use propertyExpression(for:) to apply TODO leading trivia and avoid double-wrapping.
    let arguments = propertyGenerators.enumerated().map { index, generator in
      var labeledExpr = LabeledExprSyntax(
        label: .identifier(generator.name),
        colon: .colonToken(trailingTrivia: .space),
        expression: propertyExpression(for: generator)
      )
      if index < propertyGenerators.count - 1 {
        labeledExpr = labeledExpr.with(\.trailingComma, .commaToken())
      }
      return labeledExpr as LabeledExprSyntax
    }

    let typeCallExpr = FunctionCallExprSyntax(
      calledExpression: ExprSyntax(DeclReferenceExprSyntax(baseName: .identifier(typeName))),
      leftParen: .leftParenToken(),
      arguments: LabeledExprListSyntax(arguments),
      rightParen: .rightParenToken()
    )

    let closure = ClosureExprSyntax(
      signature: ClosureSignatureSyntax(
        parameterClause: .simpleInput(
          ClosureShorthandParameterListSyntax([
            ClosureShorthandParameterSyntax(name: .identifier("composer"))
          ])
        ),
        inKeyword: .keyword(.in, trailingTrivia: .space)
      ),
      statements: CodeBlockItemListSyntax([
        CodeBlockItemSyntax(item: .expr(ExprSyntax(typeCallExpr)))
      ])
    )

    return ExprSyntax(
      FunctionCallExprSyntax(
        calledExpression: ExprSyntax(
          MemberAccessExprSyntax(
            base: ExprSyntax(DeclReferenceExprSyntax(baseName: .identifier("Gen"))),
            declName: DeclReferenceExprSyntax(baseName: .identifier("compose"))
          )
        ),
        leftParen: nil,
        arguments: LabeledExprListSyntax([]),
        rightParen: nil,
        trailingClosure: closure
      )
    )
  }

  static func propertyExpression(
    for property: GhostwriterPropertyGenerator
  ) -> ExprSyntax {
    let expression = render(expr: property.expression)
    guard let todoComment = property.todoComment else {
      return expression
    }
    return expression.with(\.leadingTrivia, [.blockComment(todoComment), .spaces(1)])
  }
}
