import Foundation

extension GhostwriterExpansionRenderer {
  /// Renders a complete generated test file.
  public static func render(file: GhostwriterGeneratedFile) -> String {
    var parts = renderHeader(for: file)

    if !file.arbitraryExtensions.isEmpty {
      parts.append("// MARK: - Auto-Generated Arbitrary Conformances")
      parts.append("")
      parts.append(
        file.arbitraryExtensions
          .map(render(arbitraryExtension:))
          .joined(separator: "\n\n")
      )
      parts.append("")
    }

    parts.append("@Suite(\(String(reflecting: file.suiteTitle)))")
    parts.append("private struct \(file.suiteTypeName) {")
    parts.append("")

    for section in file.sections {
      guard !section.tests.isEmpty else { continue }
      parts.append("  // MARK: - \(section.title)")
      parts.append("")
      parts.append(section.tests.map { indent(render(test: $0)) }.joined(separator: "\n\n"))
      parts.append("")
    }

    parts.append("}")

    return parts.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
  }

  private static func indent(_ source: String) -> String {
    source.split(separator: "\n", omittingEmptySubsequences: false)
      .map { $0.isEmpty ? "" : "  \($0)" }
      .joined(separator: "\n")
  }

  static func renderHeader(for file: GhostwriterGeneratedFile) -> [String] {
    [
      "// swiftlint:disable:next blanket_disable_command",
      "// swiftlint:disable all",
      "// swiftformat:disable all",
      "// swift-format-ignore-file",
      "// Generated by InvariantSwift Ghostwriter",
      "// Source: \(file.sourceFile)",
      "//",
      "// DO NOT EDIT - Regenerate with: \(file.regenerationCommand)",
      "",
    ] + file.imports.map(render(importDecl:)) + [""]
  }

  static func render(importDecl: GhostwriterImport) -> String {
    if let declarationKind = importDecl.declarationKind,
      let declarationName = importDecl.declarationName
    {
      return "import \(declarationKind.rawValue) \(importDecl.moduleName).\(declarationName)"
    }
    return importDecl.isTestable
      ? "@testable import \(importDecl.moduleName)"
      : "import \(importDecl.moduleName)"
  }
}
