/// RuleMacro - Peer macro for marking methods as rules
///
/// Implements `@Rule` from ISP-0003.

import SwiftCompilerPlugin
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// `@Rule` macro for marking methods as executable rules.
///
/// **Usage:**
/// ```swift
/// @Rule
/// mutating func increment() {
///     counter.increment()
/// }
///
/// @Rule(weight: 3)  // 3x more likely
/// mutating func commonOperation() { }
///
/// @Rule(into: \.users)  // Result goes into bundle
/// func createUser() -> User { ... }
/// ```
public struct RuleMacro: PeerMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    // @Rule is a marker attribute - the actual code generation
    // happens in @RuleBasedTest which collects all rules
    []
  }
}

/// `@Precondition` macro for adding preconditions to rules.
///
/// **Usage:**
/// ```swift
/// @Rule
/// @Precondition { $0.users.count > 0 }
/// func deleteUser(user: UserRef) { ... }
/// ```
public struct PreconditionMacro: PeerMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    // @Precondition is a marker attribute - collected by @RuleBasedTest
    []
  }
}

/// `@Invariant` macro for marking methods as invariants.
///
/// **Usage:**
/// ```swift
/// @Invariant
/// func modelMatchesDatabase() -> Bool {
///     model == database.snapshot()
/// }
/// ```
public struct InvariantMacro: PeerMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    // @Invariant is a marker attribute - collected by @RuleBasedTest
    []
  }
}

/// `@Bundle` macro for accumulating values across rules.
///
/// **Usage:**
/// ```swift
/// @Bundle var users: [User]
/// @Bundle var keys: [String]
/// ```
public struct BundleMacro: AccessorMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingAccessorsOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [AccessorDeclSyntax] {
    // @Bundle is primarily a marker - the accessor is generated by @RuleBasedTest
    // For now, we don't modify accessors
    []
  }
}
